// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsOVms1KALxiXSDQlwjypVagc_QCNkvIs',
    appId: '1:79022797364:android:6fe9d07069403533789061',
    messagingSenderId: '79022797364',
    projectId: 'viserbank-c4d54',
    storageBucket: 'viserbank-c4d54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfjcghVKj76lx_zIDy2Jdls8FXkapH2aQ',
    appId: '1:79022797364:ios:189ab51628331992789061',
    messagingSenderId: '79022797364',
    projectId: 'viserbank-c4d54',
    storageBucket: 'viserbank-c4d54.firebasestorage.app',
    androidClientId: '79022797364-9erloap5sp00pgcu6rlch90oekr3k65u.apps.googleusercontent.com',
    iosClientId: '79022797364-93p0foc72k8dpnqv17cqq5udhtjvtvhe.apps.googleusercontent.com',
    iosBundleId: 'dev.vlab.baseproject',
  );

}